name: MacOS

on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  macos_clang:
    name: MacOS | Clang
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        build_config: [Release, Debug]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: '3.21.0'

      - name: Setup VCPKG
        uses: lukka/run-vcpkg@v10
        with:
          # This is the glob expression used to locate the vcpkg.json and add its
          # hash to the cache key. Change it to match a single manifest file you want
          # to use.
          vcpkgJsonGlob: '**/vcpkg.json'

      - name: Build ECellEngine
        uses: lukka/run-cmake@v10
        with:
          # This is the name of the CMakePresets.json's configuration to use to generate
          # the project files. This configuration leverages the vcpkg.cmake toolchain file to
          # run vcpkg and install all dependencies specified in vcpkg.json.
          configurePreset: "Clang"
          
          # This is the name of the CMakePresets.json's configuration to build the project.
          buildPreset: "Clang ${{ matrix.build_config }}"